project_id = "jgydzxdiwpldgrqkfbfk"

[functions.invite-account-user]
verify_jwt = false

[functions.platform-provision-account]
verify_jwt = false

[functions.platform-send-password-reset]
verify_jwt = false

[functions.admin-delete-user-v3]
verify_jwt = false

[functions.admin-manage-invitation-v1]
verify_jwt = false

[functions.admin-update-membership-role-v1]
verify_jwt = false

[functions.admin-update-user-v1]
verify_jwt = false

[functions.owner-update-account-v1]
verify_jwt = false

[functions.owner-company-overview-v1]
verify_jwt = false

[functions.platform-delete-account]
verify_jwt = false

[functions.public-register-trial-v1]
verify_jwt = false

[functions.self-profile-security-v1]
verify_jwt = false
